version: '3.8'
services:
  frontend:
    build: ./
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_KEY: http://localhost:5000
  backend:
    build: ./backend
    ports:
      - 5000:5000